version: 1.0.{build}
environment:
  ClientSecret:
    secure: /8H7C81iNS+gVi7LhJCEOPUlNaa30y4KcY4nw/g2C4HGxOv6SrcroyDvMnqD+5GN
  TenantId:
    secure: xohonz/X8PPLOVIdT3ch2C5XeSa30RwR6NuXFh4e85svXT1mJNGGO1HQEGxCk3wp
  AppId:
    secure: c+H140oRJfHtmFHZxSRLWocv5AU0q33X7kgMcTcXxhJvtVhk2WAk1dRQkSN+SyoA
build_script:
- ps: >-
	.\build\BuildSolution.ps1
before_test:
- cmd: >-
    "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\sn.exe" -Vr *,*
- ps: >-
	.\build\SetXunitConfig.ps1
		
	.\build\DeployAzureResources.ps1
test_script:
- ps: >-
	.\build\RunTests.ps1
after_test:
- ps: >-
	.\build\DeleteAzureResources.ps1